<?php

return [
    'model_paths' => [
        'app' . DIRECTORY_SEPARATOR . 'Models'
    ],
    'auto_infer_migrations' => true,
    'implications' => [
        'table' => true,
        'column' => true,
        'char' => true,
        'string' => true,
        'integer' => true,
        'tinyInteger' => true,
        'smallInteger' => true,
        'mediumInteger' => true,
        'bigInteger' => true,
        'unsignedInteger' => true,
        'unsignedTinyInteger' => true,
        'unsignedSmallInteger' => true,
        'unsignedMediumInteger' => true,
        'unsignedBigInteger' => true,
        'increments' => true,
        'tinyIncrements' => true,
        'smallIncrements' => true,
        'mediumIncrements' => true,
        'bigIncrements' => true,
        'float' => true,
        'decimal' => true,
        'enum' => true,
        'set' => true,
        'time' => true,
        'timeTz' => true,
        'timestamp' => true,
        'timestampTz' => true,
        'dateTime' => true,
        'dateTimeTz' => true,
        'binary' => true,
        'geometry' => true,
        'geography' => true,
        'computed' => true,
        'index' => true,
        'unique' => true,
        'primary' => true,
        'foreign_key' => true,
        'relationship' => true,
        'pivot_table' => true,
        'pivot_column' => true,
        'off' => true,
    ],
];
